apiVersion: v1
kind: Service
metadata: 
  name: couchbase-service
  labels: 
    name: couchbase-pod
    context: docker-k8s-lab
spec: 
  ports:
    - port: 8091
      port: 8092
      port: 8093
      port: 11210
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: couchbase-rc-pod
    context: docker-k8s-lab