apiVersion: v1
kind: ReplicationController
metadata:
  name: couchbase-rc
  labels:
    name: couchbase-rc
    context: docker-k8s-lab
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: couchbase-rc-pod
        image: couchbase/server
        metadata:
          name: couchbase-rc-pod
          labels:
            name: couchbase-rc-pod
            context: docker-k8s-lab
        volumeMounts:
        - mountPath: "/opt/couchbase/var"
          name: mypd
        ports:
        - containerPort: 8091
          hostPort: 8091
        - containerPort: 8092
        - containerPort: 8093
        - containerPort: 11210
      volumes:
      - name: mypd
        persistentVolumeClaim:
          claimName: myclaim-1
