id: wildfly-controller
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 2
  replicaSelector:
    name: wildfly
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: wildfly
        containers:
          - name: javaee7-hol
            image: arungupta/javaee7-hol
    labels:
      name: wildfly